### ISSUE TITLE
(ICCV'23) VL-PET: Vision-and-Language Parameter-Efficient Tuning via Granularity Control

### ISSUE THREAD

**Issue by HenryHZY** [Computer-Vision-in-the-Wild/CVinW_Readings#4]
Hi, you might be interested in our ICCV'23 paper.
paper: https://arxiv.org/abs/2308.09804
code: https://github.com/HenryHZY/VL-PET
project page: https://henryhzy.github.io/VL-PET
baselines: LoRA, VL-Adapter, LST and etc.

**Comment by ChunyuanLI** [comment]
Added, thanks. Please feel free to submit a pull request in the future.

VL-PET: Vision-and-Language Parameter-Efficient Tuning via Granularity Control.
Zi-Yuan Hu, Yanyang Li, Michael R. Lyu, Liwei Wang.
ICCV, 2023 [[paper]](https://arxiv.org/abs/2308.09804) [[code]](https://github.com/HenryHZY/VL-PET) [[project]](https://henryhzy.github.io/VL-PET)
