### ISSUE TITLE
Request to Add Papers in Category "3D Segmentation in the Wild"

### ISSUE THREAD

**Issue by ldkong1205** [Computer-Vision-in-the-Wild/CVinW_Readings#5]
Hi @ChunyuanLI, thanks for maintaining this comprehensive repository!

I would like to recommend the following three papers under the category "[3D Segmentation in the Wild](https://github.com/Computer-Vision-in-the-Wild/CVinW_Readings#orange_book-3d-segmentation-in-the-wild)":

**CLIP2Scene: Towards Label-Efficient 3D Scene Understanding by CLIP**
Runnan Chen, Youquan Liu, Lingdong Kong, Xinge Zhu, Yuexin Ma, Yikang Li, Yuenan Hou, Yu Qiao, Wenping Wang
CVPR 2023. [[paper](https://arxiv.org/abs/2301.04926)] [[code](https://github.com/runnanchen/CLIP2Scene)]

 **Towards Label-Free Scene Understanding by Vision Foundation Models**
Runnan Chen, Youquan Liu, Lingdong Kong, Nenglun Chen, Xinge Zhu, Yuexin Ma, Tongliang Liu, Wenping Wang
NeurIPS 2023. [[paper](https://arxiv.org/abs/2306.03899)] [[code](https://github.com/runnanchen/Label-Free-Scene-Understanding)]

**Segment Any Point Cloud Sequences by Distilling Vision Foundation Models**
Youquan Liu, Lingdong Kong, Jun Cen, Runnan Chen, Wenwei Zhang, Liang Pan, Kai Chen, Ziwei Liu
NeurIPS 2023 (Spotlight). [[paper](https://arxiv.org/abs/2306.09347)] [[code](https://github.com/youquanl/Segment-Any-Point-Cloud)] [[project](https://ldkong.com/Seal)]

**Comment by ChunyuanLI** [comment]
They are added. Thanks for the great suggestions.

**Comment by ldkong1205** [comment]
Thanks for your help!
